add BLAST programs
luslab/luslab-nf-modules pull request #108
Opened 2020-10-30 09:39 UTC by mjmansfi

# luslab-nf-modules

Thank you for contributing and submitting a pull request!

Please check you have done the following:

## Uniform coding style

- [x] Used snake_case rather than camelCase
- [x] Followed the output channel naming convention (e.g. `bam` for BAM files, `bed` for BED files)

## Continuous integration

- [x] Added any new modules to `.github/workflows/modules-testing.yml`
- [x] Added any new containers to `.github/workflows/docker-build-push.yml` and `.github/workflows/docker-linting.yml`
- [x] Added any new workflows to `.github/workflows/workflow-testing.yml`
- [x] Added any new test data to `test_data`
- [x] When changing an existing module, have you bumped the version? Major.Minor.Patch - Major for breaking changes, Minor for feature updates and most things, Patch for bug fixes and small things like comment and variable name updates

## Notes

Modelled mostly after my LAST, with some differences. Each BLAST search method is a different program, so I had to add a bunch of somewhat redundant processes and entries in `module-defaults.config`. In the future maybe this could just be ${SEARCH_PROGRAM} [etc] somehow.

2020-10-30 11:58 UTC, mjmansfi commented
Guppy is failing because of `ca-certificates`. I will patch, but it will have to wait until Monday.

2020-11-02 05:04 UTC, mjmansfi commented
Should be good now.

2020-11-09 12:22 UTC, chris-cheshire requested changes

2020-11-09 12:22 UTC, chris-cheshire commented on tools/blast/main.nf
> +        tuple val(meta), path("*.asn"), emit: blast_output
can this be changed to file ext (asn)

2020-11-09 12:22 UTC, chris-cheshire commented on tools/blast/main.nf
> +        tuple val(meta), path("*.asn"), emit: blast_output
Same here

2020-11-09 12:22 UTC, chris-cheshire commented on tools/blast/main.nf
> +        tuple val(meta), path("*.asn"), emit: blast_output
Same here

2020-11-09 12:22 UTC, chris-cheshire commented on tools/blast/main.nf
> +        tuple val(meta), path("*.asn"), emit: blast_output
same here

2020-11-09 12:22 UTC, chris-cheshire commented on tools/blast/main.nf
> +        tuple val(meta), path("*.asn"), emit: blast_output
You get the idea lol

2020-11-09 12:22 UTC, chris-cheshire commented on tools/blast/test/main.nf
> +workflow {
Does this test all the modules?

2020-11-10 07:20 UTC, mjmansfi commented
Added quite a few things. 

- fix `blast_output` channel output names
- test all search programs in the test set; required adding new test files
- I had to create a `blast.config` to set various parameters. This was to prevent the nucleotide and protein databases from ever conflicting with one another

2020-11-10 07:26 UTC, chris-cheshire approved these changes

2020-11-10 08:00 UTC, merged