Add Infernal's cmscan and HMMER's hmmsearch/hmmscan tools
luslab/luslab-nf-modules pull request #109
Opened 2020-11-02 06:44 UTC by mjmansfi

# luslab-nf-modules

Thank you for contributing and submitting a pull request!

Please check you have done the following:

## Uniform coding style

- [x] Used snake_case rather than camelCase
- [x] Followed the output channel naming convention (e.g. `bam` for BAM files, `bed` for BED files)

## Continuous integration

- [x] Added any new modules to `.github/workflows/modules-testing.yml`
- [x] Added any new containers to `.github/workflows/docker-build-push.yml` and `.github/workflows/docker-linting.yml`
- [x] Added any new workflows to `.github/workflows/workflow-testing.yml`
- [x] Added any new test data to `test_data`
- [x] When changing an existing module, have you bumped the version? Major.Minor.Patch - Major for breaking changes, Minor for feature updates and most things, Patch for bug fixes and small things like comment and variable name updates

## Notes
For the test suite it uses small subsets of databases. When `cmscan` or `hmmscan` are ran as part of a pipeline, the module is written to expect the user to provide database files, which additionally need to be indexed ahead of time.

2020-11-02 07:02 UTC, mjmansfi commented
Hmm, something wrong with the `infernal` container. Investigating now.

2020-11-09 12:26 UTC, chris-cheshire requested changes

2020-11-09 12:26 UTC, chris-cheshire commented on configs/module-defaults.config
> +        'blast_makeblastdb' {
Can you move these params to the blast PR? Ho do the tests pass without them?

2020-11-09 12:26 UTC, chris-cheshire commented on tools/blast/main.nf
> +        tuple val(meta), path("*"), emit: blast_db
should this be in blast PR?

2020-11-09 12:26 UTC, chris-cheshire commented on tools/hmmer/main.nf
> +        tuple val(meta), path("*.tbl"), emit: table
output as ext name pls

2020-11-10 08:15 UTC, chris-cheshire approved these changes

2020-11-10 08:31 UTC, merged