Reduce CPU allocation to Flye
luslab/luslab-nf-modules pull request #152
Opened 2021-02-12 01:41 UTC by charles-plessy

# luslab-nf-modules

Thank you for contributing and submitting a pull request!

Please check you have done the following:

## Uniform coding style

- [ ] Used snake_case rather than camelCase
- [ ] Followed the output channel naming convention (e.g. `bam` for BAM files, `bed` for BED files)
- [ ] Set the resource label for a new process

## Continuous integration

- [ ] Added any new modules to `.github/workflows/modules-testing.yml`
- [ ] Added any new containers to `.github/workflows/docker-build-push.yml` and `.github/workflows/docker-linting.yml`
- [ ] Added any new workflows to `.github/workflows/workflow-testing.yml`
- [ ] Added any new test data to `test_data`
- [x] Bumped the version when changing an existing module
  - Major.Minor.Patch
    - Major for breaking changes
    - Minor for feature updates and most things
    - Patch for bug fixes and small things like comment and variable name updates

## Review

- [x] Selected some reviewers
- [x] Assigned yourself to the PR
- [x] Tagged the PR appropriately

2021-02-12 04:10 UTC, mjmansfi commented
As in https://github.com/luslab/luslab-nf-modules/pull/151 I think I'd call this a patch.

2021-02-15 09:50 UTC, chris-cheshire requested changes

2021-02-15 09:50 UTC, chris-cheshire commented on tools/flye/VERSION
> +1.2.0
Same here, should be 1.1.2

2021-02-16 02:25 UTC, mjmansfi approved these changes

2021-02-16 09:39 UTC, merged