Feat mod racon
luslab/luslab-nf-modules pull request #80
Opened 2020-10-01 07:50 UTC by MunissaSadykova

2020-10-01 08:25 UTC, chris-cheshire requested changes

2020-10-01 08:25 UTC, chris-cheshire commented on configs/module-defaults.config
> +				'nanoplot' {
indent needs fixing

2020-10-01 08:25 UTC, chris-cheshire commented on tools/racon/Dockerfile
> +	&& rm -rf /var/lib/apt/lists/*
you dont need this, its not installing anything

2020-10-01 08:25 UTC, chris-cheshire commented on tools/racon/main.nf
> +    container "luslab/nf-modules-racon:latest"
are you sure there isnt a biocontainer for this?

2020-10-01 08:25 UTC, chris-cheshire commented on tools/racon/main.nf
> +        tuple val(meta), path(reads), path(overlap_paf), path(assembly_fasta)
this is generally not the correct structure - you want to pass these files as separate channels unless they are directly linked to the reads file?

2020-10-01 08:25 UTC, chris-cheshire commented on tools/racon/test/nextflow.config
> +
remove line

2020-10-01 08:25 UTC, chris-cheshire commented on tools/racon/test/main.nf
> +
remove line

2020-10-01 08:25 UTC, chris-cheshire commented on tools/racon/test/main.nf
> +    racon.out.fasta | view
no channel count assertion

2020-10-01 09:30 UTC, mjmansfi commented
The `minionqc` module is failing because it points to a folder with a typo that has been fixed in this branch. Please update the minionQC `main.nf`.

2020-10-02 10:04 UTC, chris-cheshire commented
You still need to add this to the test schedule

2020-10-02 10:04 UTC, chris-cheshire requested changes

2020-10-02 10:04 UTC, chris-cheshire commented on tools/racon/main.nf
> +				path(assembly_fasta)
Tidy up indentation but good otherwise!

2020-10-06 08:36 UTC, chris-cheshire approved these changes

2020-10-06 08:59 UTC, merged